# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
#image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#cache:
#  paths:
#  - node_modules/

#build:
#  stage: build
#  script:
#  - npm install
#  - npm run build
#  artifacts:
#    paths:
#    - dist/

docker-build:
  image: docker:latest
  services:
  - name: docker:dind
    command:
    - /bin/sh
    - -c
    - wget https://docs.paas.workslan/_downloads/paas.crt -O /usr/local/share/ca-certificates/paas.crt && update-ca-certificates && dockerd-entrypoint.sh || exit
  stage: deploy
#  only:
#  - tags
  variables:
    DOCKER_REGISTRY: registry.paas.workslan
    PAAS_APP: jobhere
    DOCKER_IMAGE: $DOCKER_REGISTRY/jobhere/$PAAS_APP:$CI_COMMIT_TAG
  before_script:
  - docker login $DOCKER_REGISTRY --username $DOCKER_HARBOR_USERNAME --password $DOCKER_HARBOR_PASSWORD
  - yosolo login --username $DOCKER_HARBOR_USERNAME --password $DOCKER_HARBOR_PASSWORD
  script:
  - echo "Building docker image $DOCKER_IMAGE"
#  - docker build -t $DOCKER_IMAGE .
#  - docker push $DOCKER_IMAGE
  - echo "Deploying $PAAS_APP to paas"
#  - yosolo deploy update -a=$PAAS_APP -e=sh-stm --image=$DOCKER_IMAGE
