# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - dist/

docker-build:
  image: docker:latest
  services:
  - docker:dind
  stage: deploy
  only:
  - tags
  variables:
    DOCKER_IMAGE_NAME: registry.paas.workslan/jobhere/jobhere:$CI_COMMIT_TAG
    DIND_INSECURE_REGISTRIES: registry.paas.workslan
  script:
  - echo "Building docker image $DOCKER_IMAGE_NAME"
  - docker build -t $DOCKER_IMAGE_NAME .
  - docker login registry.paas.workslan --username $DOCKER_HARBOR_USERNAME --password $DOCKER_HARBOR_PASSWORD
  - docker push $DOCKER_IMAGE_NAME
  - yosolo login --username $DOCKER_HARBOR_USERNAME --password $DOCKER_HARBOR_PASSWORD
  - yosolo deploy update -a=jobhere -e=sh-stm --image=$DOCKER_IMAGE_NAME
